name: CI

on:
    push:
    pull_request:

jobs:
    deploy:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: ssh-scp-ssh-pipelines
              # You may pin to the exact commit or the version.
              # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
              uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
              with:
                # ssh remote host
                host: ${{ secrets.SERVER_ADDRESS }}
                # ssh remote port
                port: 1339
                # ssh remote user
                user: ${{ secrets.SERVER_USERNAME }}
                # content of ssh private key. ex raw content of ~/.ssh/id_rsa
                key: ${{ secrets.SSH_KEY }}
                first_ssh: |
                  sudo rm -rf /var/www/portfolio/
                  mkdir -p /home/${{ secrets.SERVER_USERNAME }}/portfolio
                scp: |
                  './' => /home/${{ secrets.SERVER_USERNAME }}/portfolio
                last_ssh: |
                    sudo mv /home/${{ secrets.SERVER_USERNAME }}/portfolio /var/www/portfolio/
                    cd /var/www/portfolio/
                    sudo chown www-data:www-data -R /var/www/portfolio/
                
